source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
inhibit_all_warnings!
use_frameworks!
target'MZPlayKitSDK'do

pod 'MZPushFlowSDK','2.3.0'
pod 'MZCoreSDKLibrary','2.4.0'
pod 'MZMediaSDK','2.4.1'
pod 'MZPlayerSDK','2.4.0'
pod 'MZDownLoaderSDK','2.4.0'
pod 'MZChatSDK','2.4.0'

end
