source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
inhibit_all_warnings!
use_frameworks!
target'MZPlayKitSDK'do

pod 'MZSocketIO','0.0.7'
pod 'MZPushFlowSDK','2.6.1'
pod 'MZCoreSDKLibrary','2.7.0'
pod 'MZMediaSDK','2.7.0'
pod 'MZPlayerSDK','2.6.1'
pod 'MZDownLoaderSDK','2.6.2'
pod 'MZChatSDK','2.7.1'
pod 'MZUploadVideoSDK','2.6.1'

end
